/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.kelasb23.restoranpbo;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author bayub
 */
public class Menu extends javax.swing.JPanel {
    
    private DefaultTableModel daftar_menu;
    private DefaultTableModel daftar_resep;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        daftar_menu = new DefaultTableModel();
        daftar_resep = new DefaultTableModel();
        
        main_tabel_menu.setModel(daftar_menu);
        main_tabel_resep.setModel(daftar_resep);
        
        daftar_menu.addColumn("Id Menu");
        daftar_menu.addColumn("Nama");
        daftar_menu.addColumn("Harga");
        daftar_menu.addColumn("Deskripsi");
        
        daftar_resep.addColumn("Id Bahan");
        daftar_resep.addColumn("Nama");
        daftar_resep.addColumn("Jumlah");
        daftar_resep.addColumn("Satuan");
        
        field_id_menu.setEnabled(false);
        
//        loadData();
        
        hapus_menu.addActionListener(evt ->{
            int selectedRow = main_tabel_menu.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to delete!", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this menu?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                String id_menu = (String) daftar_menu.getValueAt(selectedRow, 0);
//                deleteFromDatabase(id_menu);
            }
        });
        
        tambah_menu.addActionListener(evt ->{
//           getInput(); 
        });
        
        ubah_menu.addActionListener(evt -> {
            int selectedRow = main_tabel_menu.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to edit!", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Get current data from the selected row
            String id = (String) daftar_menu.getValueAt(selectedRow, 0);
            String nama = (String) daftar_menu.getValueAt(selectedRow, 1);
            String harga = (String) daftar_menu.getValueAt(selectedRow, 2);
            String deskripsi = (String) daftar_menu.getValueAt(selectedRow, 3);

            // Populate input fields
            field_id_menu.setText(id);
            field_nama_menu.setText(nama);
            field_harga_menu.setText(harga);
            area_deskripsi.setText(deskripsi);

            // Disable the Kode Buku field to prevent editing it
            field_id_menu.setEnabled(false);
            main_tabel_menu.setEnabled(false);

            // Change "Tambah" button to "Update" functionality
            tambah_menu.setText("Perbarui");
            hapus_menu.setEnabled(false);
            tambah_menu.removeActionListener(tambah_menu.getActionListeners()[0]);
//            tambah_menu.addActionListener(updateEvent -> updateDatabase(id));
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_container = new javax.swing.JScrollPane();
        main_tabel_menu = new javax.swing.JTable();
        resep_container = new javax.swing.JScrollPane();
        main_tabel_resep = new javax.swing.JTable();
        field_nama_menu = new javax.swing.JTextField();
        field_harga_menu = new javax.swing.JTextField();
        field_id_menu = new javax.swing.JTextField();
        container_deskripsi = new javax.swing.JScrollPane();
        area_deskripsi = new javax.swing.JTextArea();
        label_tabel_resep_menu = new javax.swing.JLabel();
        label_tabel_menu = new javax.swing.JLabel();
        tambah_menu = new javax.swing.JButton();
        hapus_menu = new javax.swing.JButton();
        ubah_menu = new javax.swing.JButton();
        label_field_id = new javax.swing.JLabel();
        label_field_nama = new javax.swing.JLabel();
        label_field_harga = new javax.swing.JLabel();
        label_field_deskripsi = new javax.swing.JLabel();

        setRequestFocusEnabled(false);

        main_tabel_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        menu_container.setViewportView(main_tabel_menu);

        main_tabel_resep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resep_container.setViewportView(main_tabel_resep);

        field_nama_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama_menuActionPerformed(evt);
            }
        });

        field_harga_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_harga_menuActionPerformed(evt);
            }
        });

        field_id_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_id_menuActionPerformed(evt);
            }
        });

        area_deskripsi.setColumns(20);
        area_deskripsi.setRows(5);
        container_deskripsi.setViewportView(area_deskripsi);

        label_tabel_resep_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_tabel_resep_menu.setText("Resep");

        label_tabel_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_tabel_menu.setText("Menu");

        tambah_menu.setText("Tambah");
        tambah_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_menu_menuActionPerformed(evt);
            }
        });

        hapus_menu.setText("Hapus");
        hapus_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_menu_menuActionPerformed(evt);
            }
        });

        ubah_menu.setText("Ubah");

        label_field_id.setText("ID");

        label_field_nama.setText("Nama");

        label_field_harga.setText("Harga");

        label_field_deskripsi.setText("Deskripsi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(tambah_menu)
                            .addGap(36, 36, 36)
                            .addComponent(hapus_menu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubah_menu))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(label_field_id))
                                .addComponent(label_field_nama)
                                .addComponent(label_field_harga, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(field_nama_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(field_id_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(field_harga_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(container_deskripsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_field_deskripsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(menu_container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addComponent(resep_container, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(label_tabel_resep_menu)
                    .addComponent(label_tabel_menu))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_tabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_container, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tabel_resep_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resep_container, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_id_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_field_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_nama_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_field_nama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_harga_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_field_harga))
                        .addGap(12, 12, 12)
                        .addComponent(label_field_deskripsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(container_deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah_menu)
                            .addComponent(hapus_menu)
                            .addComponent(ubah_menu))
                        .addGap(60, 60, 60))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void field_nama_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama_menuActionPerformed

    private void field_harga_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_harga_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_harga_menuActionPerformed

    private void tambah_menu_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_menu_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah_menu_menuActionPerformed

    private void hapus_menu_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_menu_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapus_menu_menuActionPerformed

    private void field_id_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_id_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_id_menuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_deskripsi;
    private javax.swing.JScrollPane container_deskripsi;
    private javax.swing.JTextField field_harga_menu;
    private javax.swing.JTextField field_id_menu;
    private javax.swing.JTextField field_nama_menu;
    private javax.swing.JButton hapus_menu;
    private javax.swing.JLabel label_field_deskripsi;
    private javax.swing.JLabel label_field_harga;
    private javax.swing.JLabel label_field_id;
    private javax.swing.JLabel label_field_nama;
    private javax.swing.JLabel label_tabel_menu;
    private javax.swing.JLabel label_tabel_resep_menu;
    private javax.swing.JTable main_tabel_menu;
    private javax.swing.JTable main_tabel_resep;
    private javax.swing.JScrollPane menu_container;
    private javax.swing.JScrollPane resep_container;
    private javax.swing.JButton tambah_menu;
    private javax.swing.JButton ubah_menu;
    // End of variables declaration//GEN-END:variables
}
